server:
  port: 8082

spring:
  application:
    name: ead-course-service

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL}
  instance:
    hostname: localhost

ead:
  user:
    service:
      host: 'http://localhost:8087'