server:
  port: 8082
  servlet:
    context-path: '/ead-course'

spring:
  application:
    name: ead-course-service

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL}
  instance:
    hostname: localhost

feign:
  client:
    config:
      default:
        loggerLevel: basic

logging:
  level:
    com:
      ead:
        course:
          feignclients: debug